미션3: 체스판 초기화
kyupid/java-chess-again pull request #6
Opened 2021-12-13 09:44 UTC by kyupid

2021-12-13 11:42 UTC, tmdgusya requested changes
고생하셨습니다 큐
항상 열심히 하시는게 대단하시네요!
미약하지만 리뷰 달고갑니다 :)

2021-12-13 11:42 UTC, tmdgusya commented on src/main/java/com/kyu/chess/Board.java
> +        }
2중 for 문 안에서 각 색깔별 PAWN 의 위치에 배치하는 것으로 보이는데요.

**1-depth 의 for 문에서 하는 행위(behavior) 는 무엇이고 
2-depth 의 for 문에서 하는 행위(behavior) 는 무엇일까요?**

메소드로 추출할 수 있지 않을까요? 한번 진행하셨던 미션이니 좀 더 생각할 거리를 던져봅니다.

2021-12-13 11:42 UTC, tmdgusya commented on src/main/java/com/kyu/chess/Board.java
> +        for (String[] strings : map) {
map 에 놓여져있는건 무엇일까요?

strings 라는 변수로 표현하는 것보다 더 Context 를 잘 나타낼 수 있도록 하는게 좋아보입니다.

2021-12-13 11:42 UTC, tmdgusya commented on src/main/java/com/kyu/chess/Board.java
> +            for (String str : strings) {
위와 같습니다.

2021-12-13 11:42 UTC, tmdgusya commented on src/main/java/com/kyu/chess/Main.java
> +        while (scanner.next().equals("y")) {
scanner.next().equals("y") 도 메소드로 추출할 순 없을까요?
메소드로 좀 더 의미있는 표현을 할 수 있다고 생각되네요.

2021-12-13 11:42 UTC, tmdgusya commented on src/test/java/com/kyu/chess/BoardTest.java
> +        board.initialize();
테스트 라기보다는 Console Debugging 과 비슷하다고 생각되네요.
무언가 행위에 대한 결과를 체크할 수 있도록 테스트할 순 없을까요?

2021-12-13 11:42 UTC, tmdgusya commented on src/test/java/com/kyu/chess/pieces/PawnTest.java
> +        assertThat(pawn.getRepresentation()).isEqualTo(representation);
👍

2021-12-13 11:42 UTC, tmdgusya commented on src/test/java/com/kyu/chess/pieces/PawnTest.java
>      @DisplayName("색이 없는 폰을 만든다.")
DisplayName 을 통해 기능에 대한 의도(명세)를 좀 더 드러내는게 좋지 않을까 싶은데요.
예를 들면 아래와 같은 테스트는 처음 생성될 시 Representor 와 Color 가 Null 로 생성되는거 같은데

@DisplayName("Pawn 을 생성할시 기본으로 Color 와 Representation 이 Null 인지 확인한다") 
위처럼 적는게 조금 더 의도를 잘 드러내는 것이 아닐까 싶네요 
한번 고민해보시는 것도 좋을 거 같습니다.

2021-12-13 12:12 UTC, kyupid commented on src/main/java/com/kyu/chess/Board.java
> +        for (String[] strings : map) {
앗 그렇네요. 앞으론 네이밍에 더 신경써봐야겠습니다 !

2021-12-13 12:33 UTC, kyupid commented on src/main/java/com/kyu/chess/Main.java
> +        while (scanner.next().equals("y")) {
확실히 메소드로  따로 분리하니 의미가 분명하게 들어나는 효과가 있네요 :)
근데 이름 짓기는 한참을 고민해봤지만 잘 모르겠네요 ㅎㅎ 일단 수정했습니다

2021-12-13 13:02 UTC, kyupid commented on src/test/java/com/kyu/chess/pieces/PawnTest.java
>      @DisplayName("색이 없는 폰을 만든다.")
맞습니다. 이 DisplayName은 테스트하려는 것의 의미를 완전히 담지 못하고 있어요

2021-12-13 13:02 UTC, kyupid commented on src/test/java/com/kyu/chess/BoardTest.java
> +        board.initialize();
흠..저도 이걸 어떻게 테스트를 해야할지 잘 모르겠더라구요.
"행위에 대한 결과를 체크"  할수 있게 하려면
제생각엔 `initialize()`에 쓰이는 변수(이차원배열)를 가지고 와야할거 같다고 생각했어요.
그래서`Board` 클래스에 필드`map` 에 대한 getter 를 만들었어요
그런데 **테스트를 위해서 코드를 변경해야한다는 것**이 조금 신경쓰여서 잘못 생각한건가 싶지만, 일단은 한번 그렇게 변경해봅니다.

이부분에 대한 커밋 링크 달았습니다.. 제가 변경한 테스트가 맞는건지 궁금하네요.

2021-12-13 13:08 UTC, kyupid commented on src/main/java/com/kyu/chess/Board.java
> +        }
흠,,,,,이건 내일 지하철에서 한번 다시 생각해봐야겠어요.

2021-12-14 01:06 UTC, tmdgusya commented on src/main/java/com/kyu/chess/Board.java
> +        }
네네 객체지향 생활체조 관련해서 보시면 하나의 인덴트만 유지하는 법칙이 있는데 그걸보면 힌트가 되실겁니다.

2021-12-14 01:07 UTC, tmdgusya commented on src/main/java/com/kyu/chess/Main.java
> +        while (scanner.next().equals("y")) {
개발자 개발시간은 전부 변수, 함수명 짓는데 다쓴다는 말이 있죠 ㅠㅠ..

2021-12-14 01:08 UTC, tmdgusya commented on src/test/java/com/kyu/chess/BoardTest.java
> +        board.initialize();
네네 좋은거 같네요 :)

2021-12-14 06:44 UTC, kyupid commented on src/main/java/com/kyu/chess/Board.java
> +        }
알려주셔서 감사합니다. 찾아보니 2중포문이 대표적인 예시로 많이 나오네요

2021-12-14 06:45 UTC, kyupid commented on src/main/java/com/kyu/chess/Board.java
> +        }
오늘 그 외에 나머지 객체지향 생활체조도 정리해봐야겠습니다 !

2021-12-14 08:38 UTC, ghojeong requested changes
저도 뒤늦게 리뷰 달아보았습니다.

`while (selectedCommandToStartGame()) {`
에 대해서만 답변 주시면, 

나머지는 굳이 진지하게 반영하지 않아도 될것 같습니다.
혹시 피드백 어려우시면 Zoom 통한 화상통화나 질문 언제든 환영합니다.

2021-12-14 08:38 UTC, ghojeong commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
지금 Pawn 의 color 는 BLACK 혹은 WHITE 2가지 색깔 밖에 없다고 생각되는데,
enum { BLACK, WHITE } 로 분리하는 것은 어떨지 제안해봅니다.

혹시 나중에라도, YELLOW 혹은 PURPLE 색깔이 추가되는게 아니라면, 타입체크를 할 수 있도록 단순한 String 이 아니라,
enum 으로 만들면 어떨까요?

또한 Color enum 에 따라 representation 이 달라지도록 하는 로직을
(즉, String.toUpperCase 혹은 String.toLowerCase) 로직을 Pawn 이 아니라,
Color enum 이 갖도록 하면 어떨까 제안을 해봅니다.

2021-12-14 08:38 UTC, ghojeong commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
참고로 이건 단순한 제안이므로, 꼭 제 말대로 하지 않으셔도 됩니다.
이건 매우 조슈아 블로크의 "이펙티브 자바" 스러운 설계이고, (이 분은 enum 성애자 입니다.)
엘레강트 오브젝트에서는 enum 사용을 이렇게 권장하지는 않습니다.

2021-12-14 08:38 UTC, ghojeong commented on src/main/java/com/kyu/chess/Game.java
> +    }
반환타입이 boolean 이라는 것을 누구나 알 수 있도록, 메서드 명을 좀더 신경쓰면 좋을 것 같습니다.
저는 `selectedCommand` 에서 반환 타입이 String 이라고 생각했었습니다.

2021-12-14 08:38 UTC, ghojeong commented on src/main/java/com/kyu/chess/Game.java
> +        }
```suggestion
        if (!selectedCommandToStartGame()) {
            return;
        }
        Board board = new Board();
        board.initialize();
        System.out.println("start? y or n");
        // TODO: 체스말 액션
```

혹시 이게 의도하신 로직이 아닌지 여쭈어봅니다.
start 를 y 를 입력하면, 무한히 게임을 초기화할 수 있다는게 잘 이해가 가질 않아서요.
y 를 계속 누르는 한, 네버엔딩 게임이 되도록 하는게 큐가 의도하신게 맞나요?

n 을 눌렀을때, 게임이 진행되지 않고 종료되도록 하는게 Kyu 의 의도가 아닐까 해서 여쭈어봅니다.

2021-12-14 08:38 UTC, ghojeong commented on src/main/java/com/kyu/chess/Board.java
> +    }
String piece 원시값을 Piece class 로 포장하고,
Pieces 일급 컬렉션, Map 일급 컬렉션, Board 일급 컬렉션을 적용해보면 딱 적절하겠네요!
지금은 작업이 많아질 것 같으니,
나중에 혹시 일급 컬렉션을 본인에 코드에 응용해보고 싶으시면 도전하면 될것 같습니다.

2021-12-14 09:03 UTC, kyupid commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
사실 `color`는 `PieceColor` 클래스에서 enum 으로 나누어주고 있어요.
근데 `REPRESENTATION` 을 색상별로 따로 `Pawn` 같은 `Piece` 클래스 안에 선언한 건 이유가있는데요.
enum으로 사용시에 아래처럼 하려고했었어요.
```java
public enum PieceRepresentation {
    WHITE_KING("k", "white"),
    WHITE_QUEEN("q", "white"),
    WHITE_BISHOP("b", "white"),
    WHITE_KNIGHT("n", "white"),
    WHITE_ROOK("r", "white"),
    WHITE_PAWN("p", "white"),

    BLACK_KING("K", "black"),
    BLACK_QUEEN("Q", "black"),
    BLACK_BISHOP("B", "black"),
    BLACK_KNIGHT("N", "black"),
    BLACK_ROOK("R", "black"),
    BLACK_PAWN("P", "black");

    private String representation;
    private String color;

    PieceRepresentation(String representation, String color) {
        this.representation = representation;
        this.color = color;
    }

    public String getRepresentation() {
        return representation;
    }

    public String getColor() {
        return color;
    }
}
```
위와같이 색상까지 같이 주는 형식으로 하려고 했는데
지금은..음.. 기억이 안나는데 어딘가에서 한번 구현에 막혀서 다시 되돌렸었네요 ..ㅎㅎ
일단은 그래서 구현하기 쉬운방향으로 했고,
나중에 리팩토링 가능하다면 고려해보려고 했어요! 물어봐주셔서 감사합니다 :)

그리고 저는 개인적으로 enum 사용이 그냥 필드에 선언하는거보다 더 재밌다고 생각하는데 언젠가 이펙티브 자바 꼭 독해해보고 싶네요.

2021-12-14 09:05 UTC, kyupid commented on src/main/java/com/kyu/chess/Game.java
> +    }
헛 그렇네요. 근데 네이밍이 너무 어렵습니다 파교수님...ㅠㅠ
 `isYesToStartGame` 정도가 좋으려나요. 요렇게 한번 적용해보겠습니당.

2021-12-14 09:09 UTC, ghojeong commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
`BLACK_QUEEN` 흠...
enum 의 네임과 실제 representation 및 color 가 깊은 연관관계를 맺고 있다는 점에서,
이펙티브 자바 아이템 39의 "명명 패턴보다 애너테이션을 사용하라"가 떠오르는 군요.

저는 객체의 네임이 실제 상태값 혹은 객체 로직과 지나치게 연관이 깊으면,
사실 책임을 분리할 수 있는게 아닐까 의심하고는 합니다.
즉 `BLACK_QUEEN` 은 "BLACK" 과 "QUEEN" 으로 분리될수 있지 않을까 생각하는 것이죠.

근데 이건 조슈아 블로크를 맹신하는 편집증적인 피드백 같습니다.
저는 지금의 설계도 충분히 만족스러운것 같습니다.
그냥 지나가는 한마디라 생각하시고, 굳이 반영하려 하지 마세요.

2021-12-14 09:10 UTC, ghojeong commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
정말로 충분히 잘 설계해주셨습니다.
여기에 시간을 많이 쏟기 보다는, 다른 기능구현에 진도를 많이 빼는 것이 훨씬 나을 것 같습니다.

2021-12-14 09:12 UTC, kyupid commented on src/main/java/com/kyu/chess/Game.java
> +        }
게임을 시작하고 난뒤에 무한히 게임을 초기화하기보다
여러가지 액션들이 취해질거같아서 일단은 y를 누르면 계속해서 체스판이 나오기 때문에,
게임을 진행한다는 느낌이어서 그렇게 했는데요. 사실..그렇게 생각하고 작성한건 아니었어요
말씀해주신거 보니 수정해주신 코드가 제가 의도하려던게 맞는거 같습니다 ㅎㅎ 감사합니다

2021-12-14 09:13 UTC, kyupid commented on src/main/java/com/kyu/chess/Board.java
> +    }
오호 오늘 로치,파이로 pr덕분에 공부할 소스들을 많이 얻은거 같아 좋네요!!
염두해두고 나중에 기회되면 시도해보겠습니다!!

2021-12-14 09:18 UTC, kyupid commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
> 즉 BLACK_QUEEN 은 "BLACK" 과 "QUEEN" 으로 분리될수 있지 않을까 생각하는 것이죠.

다시 생각해보니 정말 그런거 같은데요? ㅎㅎ

2021-12-14 09:18 UTC, kyupid commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
넵 머지하고 미션4로 가겠습니다. 리뷰 감사드려요

2021-12-14 09:19 UTC, merged

2021-12-15 08:03 UTC, kyupid commented on src/main/java/com/kyu/chess/pieces/Pawn.java
> +    private String representation;
아..미션5로 왔는데 구현해놓고보니 두가지 상태가 같이있으니까 
뭐 죽은말인지 속성을 하나 추가하려는데 힘드네요..ㅠㅠ
책임분리를 해야할거같아요